### ISSUE TITLE
Placeholder for top longest survival times

### ISSUE THREAD

**Issue by cafestifflered** [GamerSafer/ablockalypse#9]
Expand `%ablockalypse_survivaltime%` to the following

`%ablockalypse_alltop_survivaltime_one%` - Shows the top survival times for all players like a leaderboard
`%ablockalypse_alltop_survivaltime_two%`
`%ablockalypse_alltop_survivaltime_three%`
`%ablockalypse_alltop_survivaltime_four%`
`%ablockalypse_alltop_survivaltime_five%`

`%ablockalypse_top_survivaltime%` - Shows the top survival time for the player viewing the placeholder

Reference TF-PvEvP examples of top scores if needed

**Comment by cafestifflered** [comment]
Three different placeholders for each:
- Playername
- Time
- What was their backstory

**Comment by SpaicyGaming** [comment]
The implemented system is slightly different than how it's described above.
there is a new config section:
```
leaderboard:
  # How often should the leaderboard be updated?
  refresh-interval-seconds: 300
  # How many stories should be included in the leaderboard?
  max-entries: 10
```
`max-entries` determines how many entries will be loaded on the leaderboard. 

the new PAPI placeholders are:
```
%ablockalypse_alltop_survivaltime_X_name%
%ablockalypse_alltop_survivaltime_X_playtime%
%ablockalypse_alltop_survivaltime_X_character%
```
`X` is a number between 1 and `max-entries` inclusive. This allows server admins to create a leaderboard as long as they prefer.
